os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/fabafba485630f6d8280e29e8afbd4a0/raw/1c364252bc56d9bbb142cd2396158994eb795ac4/mysql)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql.server start; fi
before_script:
  - cp "$TRAVIS_BUILD_DIR/test/.my.cnf" ~/.my.cnf
  - >
    sudo mysql -e "CREATE DATABASE batch;
    CREATE USER 'batch' IDENTIFIED BY 'test';
    GRANT ALL ON batch.* to 'batch';"
  - >
    mysql --defaults-group-suffix=batch -e "CREATE TABLE episode
    (number TINYINT NOT NULL,
    date DATE NOT NULL,
    media_url VARCHAR(1024) NOT NULL,
    PRIMARY KEY (number),
    INDEX (date));
    CREATE TABLE track
    (episode_number TINYINT NOT NULL,
    start_time TIME NOT NULL,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    PRIMARY KEY (episode_number, start_time),
    FOREIGN KEY (episode_number) REFERENCES episode (number) ON DELETE CASCADE);"
script:
  - eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/a031003addffa3201205a029ff68d146/raw/a9d94ac6f6107bd20805f42e931a7b385b9873f6/ci)"
