os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
before_script:
  - cp "$TRAVIS_BUILD_DIR/test/.my.cnf" ~/.my.cnf
  - >
    mysql -u root -e "CREATE DATABASE batch;
    CREATE USER 'batch' IDENTIFIED BY 'test';
    GRANT ALL ON batch.* to 'batch';"
  - >
    mysql --defaults-group-suffix=batch -e "CREATE TABLE episode
    (number TINYINT NOT NULL,
    date DATE NOT NULL,
    media_url VARCHAR(1024) NOT NULL,
    PRIMARY KEY (number),
    INDEX (date));
    CREATE TABLE track
    (episode_number TINYINT NOT NULL,
    start_time TIME NOT NULL,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    PRIMARY KEY (episode_number, start_time),
    FOREIGN KEY (episode_number) REFERENCES episode (number) ON DELETE CASCADE);"
script:
  - swift build
  - swift build -c release
