os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/dd728a46bbc889b22b9470432092933c/raw/8f9bf0c21bd40231b39f8187b0c534d917f8cc27/mysql)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated mysql || brew upgrade mysql; fi
before_script:
  - cp "$TRAVIS_BUILD_DIR/test/.my.cnf" ~/.my.cnf
  - >
    mysql -u root -e "CREATE DATABASE batch;
    CREATE USER 'batch' IDENTIFIED BY 'test';
    GRANT ALL ON batch.* to 'batch';"
  - >
    mysql --defaults-group-suffix=batch -e "CREATE TABLE episode
    (number TINYINT NOT NULL,
    date DATE NOT NULL,
    media_url VARCHAR(1024) NOT NULL,
    PRIMARY KEY (number),
    INDEX (date));
    CREATE TABLE track
    (episode_number TINYINT NOT NULL,
    start_time TIME NOT NULL,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    PRIMARY KEY (episode_number, start_time),
    FOREIGN KEY (episode_number) REFERENCES episode (number) ON DELETE CASCADE);"
script:
  - eval "$(curl -sL https://gist.githubusercontent.com/bakemecookies/87f4a44ee282206b4e32ace78847c180/raw/f5261dd24f534eb7b35050336c1964c68b4c2119/ci)"
